add order to questions in a set
3PillarGlobal-Czechia/interview-app-api pull request #68
Opened 2022-03-28 08:59 UTC by TomasNiemczyk98

## Summary

Created a new table for many to many relation between questions and question sets which contains their order. Questions returned from repository are already ordered.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Refactoring (non-breaking change to code and structure)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-03-28 12:26 UTC, PlesnikJakub requested changes
The large portion of this PR is going to be fine but there are some areas where it feels not ideal.

1. Repository - not sure if we need a separate one for this purpose, it would be just fine to transfer this responsibility to QuestionSetRepository. 

2. I think the domain should know nothing about the relationship table, it only matters to get the order of questions. Thus API is expected to return an attribute with each question as an "order" or "sortKey".  I definitely don't want to send relationship representation over to the domain.

2022-03-28 12:26 UTC, PlesnikJakub commented on src/WebApi/Domain/Models/QuestionSetQuestionModel.cs
> +    public QuestionModel InterviewQuestion { get; set; }
I don't see this model being very useful, it feels overcomplicated 🤔

2022-03-28 12:28 UTC, PlesnikJakub commented
We could use some brainstorming for the design of this feature.
@fpindej  @petrspelos

2022-03-28 13:15 UTC, TomasNiemczyk98 commented on src/WebApi/Application/Repositories/IQuestionSetQuestionRepository.cs
> +    Task<bool> Remove(int listId, int questionId);
Yeah that makes sense, the model was only necessary as type parameter for generic repository with the repository being removed there is no need for it anymore

2022-03-30 09:05 UTC, PlesnikJakub approved these changes
ship it 🚀

2022-03-30 09:10 UTC, merged