Feature/delete question
3PillarGlobal-Czechia/interview-app-api pull request #78
Opened 2022-04-01 10:11 UTC by TerezaSkutova

## Summary

🚨 Provide a brief summary of your work.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactoring (non-breaking change to code and structure)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Testing

🚨 Provide info about the new tests and tests result

## Notes

🚨 Anything else

2022-04-01 12:25 UTC, TomasNiemczyk98 reviewed
Looks good, just one small thing, throughout the project we are trying to use [file scoped namespaces](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces) so, if you could look into that 🙂

2022-04-01 13:59 UTC, PlesnikJakub requested changes
a couple of small suggestions to make it even better :)

2022-04-01 13:59 UTC, PlesnikJakub commented on src/WebApi/Application/UseCases/Question/DeleteInterviewQuestion/DeleteQuestionInput.cs
> +{
As Tomas mentioned, this should be a rather file-scoped namespace. You can change that through the contextual menu after right-clicking on namespace there is an auto-conversion tool.

If interested, here are the specs
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

2022-04-01 13:59 UTC, PlesnikJakub commented on src/WebApi/UnitTests/Tests/Application/UseCase/QuestionTests/DeleteQuestionUseCaseTest.cs
> +            Id= 1
Just a minor styling issue with a suggestion
```suggestion
            Id = 1
```

2022-04-01 13:59 UTC, PlesnikJakub commented on src/WebApi/UnitTests/Tests/Application/UseCase/QuestionTests/DeleteQuestionUseCaseTest.cs
> +
```suggestion
```

2022-04-05 11:11 UTC, PlesnikJakub approved these changes
Good job 😊 🚀

2022-04-05 11:12 UTC, PlesnikJakub submitted a review, later dismissed

2022-04-05 12:42 UTC, TomasNiemczyk98 approved these changes
:shipit:

2022-04-05 12:43 UTC, merged